id: P000177
initial_creation_type: ebook
source_metadata:
  title: རྩ་བའི་རྒྱུད་ཀྱི་མཆན་འགྲིལ་ཉི་ཟླའི་སྙིང་པོ། །
  authors:
  - མཛད་པ་པོ། གཞན་ཕན་སྣང་བ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: SHE-008
web_metadata:
  title:
    en: The Essence of the Sun and Moon:A Commentary on the Root Tantra
    bo: རྩ་བའི་རྒྱུད་ཀྱི་མཆན་འགྲིལ་ཉི་ཟླའི་སྙིང་པོ།
  collection:
    en: Shechen Tantra Series–  Book 8
    bo: ''
  author:
    en: Shenphen Nangwa
    bo: གཞན་ཕན་སྣང་བ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-008
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-008.epub
  description:
    en: ''
    bo: ''
